remote_theme: mmistakes/jekyll-theme-academic

header_pages:
  - index.md
  - about.md
  - classes.md
  - thesis.md
plugins:
 - jekyll-remote-theme

footer:
  links:
    - title: "Twitter"
      url: twitter.com
