remote_theme: b2a3e8/jekyll-theme-console
header_pages:
  - index.md
  - notes.md
  - links.md 
  - about.md
footer: <img src="https://hitcounter.pythonanywhere.com/count/tag.svg" alt="Hits">
style: light
